<?php

namespace CPLN\Modules\DaemonModule\Services;


use Plexus\AbstractRuntime;
use Plexus\Exception\PlexusException;
use Plexus\Model;
use Plexus\ModelSelector;
use Plexus\Service\AbstractService;
use Plexus\Utils\Randomizer;
use Plexus\Utils\Text;

class DaemonLogService extends AbstractService {

    /**
     * @param AbstractRuntime $runtime
     * @param mixed ...$options
     * @return DaemonLogService
     */
    public static function fromRuntime(AbstractRuntime $runtime, ...$options) {
        return parent::fromRuntime($runtime, $options); // TODO: Change the autogenerated stub
    }

    public function get($daemon_identifier, $log_index=null) {
        $logManager = $this->getModelManager("daemon_log");
        if ($log_index !== null) {
            $logs = $logManager->select(
                ModelSelector::where(
                    "daemon_identifier = :daemon_identifier",
                    ['daemon_identifier' => $daemon_identifier]
                ),
                ModelSelector::where(
                    "id > :log_index",
                    ['log_index' => $log_index]
                ),
                ModelSelector::order("created_on", "DESC")
            );
        } else {
            $logs = $logManager->select(
                ModelSelector::where(
                    "daemon_identifier = :daemon_identifier",
                    ['daemon_identifier' => $daemon_identifier]
                ),
                ModelSelector::order("created_on", "DESC")
            );
        }

        return $logs;
    }

    public function logMessage($daemon_identifier, $message, $time=null) {
        $logManager = $this->getModelManager("daemon_log");
        $log = $logManager->create();
        $log->daemon_identifier = $daemon_identifier;
        $log->message = $message;
        if ($time !== null) {
            $log->created_on = date("Y-m-d H:i:s", intval($time));
            $logManager->insert($log);
        } else {
            $logManager->insert($log, [
                'created_on' => 'NOW(3)'
            ]);
        }

    }

}